services:
  rabbitmq:
    image: rabbitmq:management
    container_name: ingressinhos-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: ***REMOVED***
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq # Persistência dos dados até serem consumidos

volumes:
  rabbitmq-data:
