@Payment.Api_HostAddress = http://localhost:5071

POST {{Payment.Api_HostAddress}}/api/payments/transactions
Content-Type: application/json

{
  "orderId": 1,
  "amount": 149.90,
  "method": "pix"
}

###

POST {{Payment.Api_HostAddress}}/api/payments/transactions/1/simulate-webhook
Content-Type: application/json

{
  "status": "approved"
}

###
