events {
    worker_connections 1024;
}

http {
    server {
        # O Nginx escuta na 8080 dentro do container
        listen 8080;
        
        # Rota para o serviço de Autenticação
        location /auth/ {
            # Usa o nome do container (auth-api) e a porta interna (8080)
            proxy_pass http://auth-api:8080/;
            proxy_set_header Host $host;
        }

        # Rota para o serviço de Pagamento
        location /payment/ {
            proxy_pass http://payment-api:8080/;
            proxy_set_header Host $host;
        }

        # Rota para a tela de Mock (que também vive no payment-api)
        location /mock/ {
            proxy_pass http://payment-api:8080/;
            proxy_set_header Host $host;
        }

        # Rota principal para o projeto de Ingressinhos
        location / {
            proxy_pass http://ingressinhos-api:8080/;
            proxy_set_header Host $host;
        }
    }
}